/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface HealthButton {
    'title': string;
  }
}

declare global {


  interface HTMLHealthButtonElement extends Components.HealthButton, HTMLStencilElement {}
  var HTMLHealthButtonElement: {
    prototype: HTMLHealthButtonElement;
    new (): HTMLHealthButtonElement;
  };
  interface HTMLElementTagNameMap {
    'health-button': HTMLHealthButtonElement;
  }
}

declare namespace LocalJSX {
  interface HealthButton extends JSXBase.HTMLAttributes<HTMLHealthButtonElement> {
    'title'?: string;
  }

  interface IntrinsicElements {
    'health-button': HealthButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


